TESTS WITH ERRORS --------------------
-------------------------------
TESTS FAILED  --------------------
test_2 (__main__.UnitTests)
Traceback (most recent call last):
  File "tests.py", line 87, in test_2
    self.assertEqual(ans[0], gold)
AssertionError: Lists differ: [[], [], [], []] != [((3, 1), (1, 1)), ((3, 3), (3, 1)), ((1, [43 chars] 0))]

First differing element 0:
[]
((3, 1), (1, 1))

Second list contains 1 additional elements.
First extra element 4:
((2, 0), (0, 0))

- [[], [], [], []]
+ [((3, 1), (1, 1)),
+  ((3, 3), (3, 1)),
+  ((1, 3), (3, 3)),
+  ((0, 0), (0, 2)),
+  ((2, 0), (0, 0))]

test_3 (__main__.UnitTests)
Traceback (most recent call last):
  File "tests.py", line 109, in test_3
    self.assertEqual(ans[0], gold)
AssertionError: Lists differ: [[], [], []] != [((0, 1), (2, 1)), ((3, 0), (3, 2)), ((2, 1), (2, 3)), ((1, 0), (3, 0))]

First differing element 0:
[]
((0, 1), (2, 1))

Second list contains 1 additional elements.
First extra element 3:
((1, 0), (3, 0))

- [[], [], []]
+ [((0, 1), (2, 1)), ((3, 0), (3, 2)), ((2, 1), (2, 3)), ((1, 0), (3, 0))]

-------------------------------
TESTS SKIPPED --------------------
-------------------------------
